version: '3.7'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-12.5}
    container_name: postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    restart: always

networks:
  postgres:
    name: postgres
    driver: bridge
